### ISSUE TITLE
0.045tr - Player hitbox barely visible

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#10]
Player hitbox graphic is barely visible. It requires much better contrast with the player itself, and the tiny red circle seems to be smaller than the actual player hitbox.

**Comment by bluebear94** [comment]
I can swear that I drew the dot bigger than the actual hitbox. Maybe it _is_ the blending in.

**Comment by Sparen** [comment]
I think having the entire structure bigger and rotating will make it clearer where the actual hitbox is. Right now, the entire structure blends in with the player graphic, with little to no contrast

**Comment by bluebear94** [comment]
How to rotate a 2D render object?
