### ISSUE TITLE
0.045tr - Music Room missing stages 6-9

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#18]
Music Room is missing tracks from Stages 6-9.

**Comment by bluebear94** [comment]
Will be fixed as soon as the whole music room text is written and translated into Fluffyese.

(Even the English version doesn't have comments for the music that's already there, and I have 3 remaining.)

**Comment by bluebear94** [comment]
As of 3dde9861ce452e557b0d0ad686b9f2af95e2fac6, all of the music room entries are present.
