### ISSUE TITLE
0.045tr - Stage 10 dialogue mentions a blizzard; no blizzard anywhere

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#19]
Currently, as of bff3441f37c0235f4c767d12ebc0566b150a911e, Stage 10's dialogue mentions a blizzard. However, there is no blizzard of any sort in the background.

This is a general graphical feature update.

**Comment by bluebear94** [comment]
Should this be merged with #20?

**Comment by Sparen** [comment]
Yes. It should.
