### ISSUE TITLE
0.045tr - Unclear how to select player in Spellcard Practice

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#2]
Currently, you switch player types in Spellcard Practice by hitting left or right keys. However, this needs to be made more clear. Perhaps have a line of text at the bottom of the screen that states how to change players?

**Comment by bluebear94** [comment]
Fixed in 4a3ad3c.

**Comment by Sparen** [comment]
The new text remains when a spell has been selected, and the text is visible in the following spell card..

**Comment by bluebear94** [comment]
Derp, you should have opened a new issue in that case.

**Comment by bluebear94** [comment]
Fixed in 84b84eeeec15d736297956d4b1b6033a1d672312.
