### ISSUE TITLE
0.045tr - Stage 10 Boss Spell 1 Balancing

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#22]
In the current (bff3441f37c0235f4c767d12ebc0566b150a911e) Stage 10 Boss's First Spell, the defensive icicles appear out of nowhere at a very high speed. Since the point of defensive bullets is to warn the player not to get too close to the boss, the existing mechanism is ineffective and cheap.

Additionally, the premise of the spell card itself is extremely simple and extremely boring, as on lower difficulties, all that needs to be done is to move left, wait, repeat.

**Comment by bluebear94** [comment]
There's a reason Easy mode is called Easy mode. On Normal and higher, there is another line of icicles. Also, many a spell seems cheap to someone who has never played it before.
