### ISSUE TITLE
0.045tr - Laser Rygen - Unable to shoot after bomb

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#26]
When bombing focused with Laser Rygen (as of bff3441f37c0235f4c767d12ebc0566b150a911e), Rygen does not automatically begin shooting once the bomb is complete. This may be intentional, or may be a bug due to variables not being reset.

**Comment by bluebear94** [comment]
Please clarify which Rygen you're discussing (A or B), since both use lasers.

**Comment by Sparen** [comment]
RygenA
