### ISSUE TITLE
0.045tr - Item collect score text rendered as GandalfRunes

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#3]
Item collect text is currently rendered as pixel-thick runes that are completely unreadable due to their thinness, their nature as runes, and the overlapping of different texts at once. Suggest to replace with actual numbers

**Comment by bluebear94** [comment]
I was starting on this enhancement yesterday. It's already possible to choose which image is used, but I still have to implement using a custom image.

**Comment by Sparen** [comment]
You can always use a text object with a font. It's simpler that way, since you don't need to use SpriteList Primitives (assuming you already do)

**Comment by bluebear94** [comment]
I already do, and implementing the possibility of different spritefonts is easier to do.

Plus I want to keep the runes for the Fluffyese language pack.

**Comment by Sparen** [comment]
OK. Just be aware of the DirectX power of 2 issue when you make your images, as always

**Comment by bluebear94** [comment]
Fixed in 84b84eeeec15d736297956d4b1b6033a1d672312.
