### ISSUE TITLE
0.045tr - Stage 1 Static 2D Sprite in Background

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#34]
When a bomb uses screenshake, the 2D component also shakes. However, the image selection is not large enough, so the black parts show. To rectify this, change the destrect of the 2D component or make it unaffected by the 2D Camera.

Present as of 6f245d975e169e0b0ef043a3f6050b9ddc42a452, Stage 1 Background

**Comment by bluebear94** [comment]
Fixed in 93bec0c7261548f75b7b294fa7c8dd916f3ed5b2.
