### ISSUE TITLE
0.10tr - Stage 1 background too bright

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#38]
Stage 1's background is very bright, obscuring enemy bullets, player shots, and providing either poor or excessive contrast with most of the graphics.

To remedy, use a less bright sky image and perhaps a darker ground.

**Comment by bluebear94** [comment]
Would the new background in 8cd9fe337637652e2ed7c1658b6a60331f0334d7 help?

**Comment by bluebear94** [comment]
Related: Rencron A shots blend in.

**Comment by bluebear94** [comment]
I really didn't like doing it, but the background was darkened yet again in 084f636f30478935b1e5cf542715c38f8eb1defe. Shots should blend in less now.
