### ISSUE TITLE
0.10tr - Spell Capture text screwed up

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#39]
Sometimes, other numbers are rendered below the ones normally rendered, other times the borders are all screwy. May be the same issue. As of f1f28215df395a2a00c9dcd4a9e9d39987ff6be4

**Comment by bluebear94** [comment]
~~I have near no idea why this is happening.~~

It appears that the spell capture task is being called twice. That also means that the bonus is added to the score twice as well. Don't know where it's being called again, though.
