### ISSUE TITLE
1.00a - Stage 10 Boss has a Survival Spell

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#42]
Just curious, why does the final? boss have a survival spell? Usually 120 second survivals are limited to Extra Stages because they require memorization and don't fit in the normal game.

**Comment by bluebear94** [comment]
Because why not?

**Comment by Sparen** [comment]
Let's not discuss this further, because all you're going to get is complaints about it. Survivals are tests of endurance and memorization. They do not belong in the main game, where players are trying to clear the game
