### ISSUE TITLE
1.00a - Shot Types weakened

### ISSUE THREAD

**Issue by ghost** [bluebear94/cy05#46]
When I was playing your game. (The full version.) I discovered that Rencron A (The shotype that i used in the previous version I played.) was much weaker. This made it a pain to kill even the basic enemies that shot the most basic patterns. And his bomb was also weakened to my knowledge as once again, the enemies that would normally die to the boss straight away to such a bomb were not dying and in some cases; not even being phased by it. 
This made stage 3 a major pain as I wasn't able to kill the enemies fast enough; and you clearly intended for them to be killed quickly.

**Comment by Sparen** [comment]
I'm pretty sure buffing RencronA is going to make Mernen go down in 5 seconds again...

**Comment by bluebear94** [comment]
Do you want me to undo the changes then?

**Comment by Sparen** [comment]
It's fine because you implemented the invincibility frames. So don't change the DPS again
