### ISSUE TITLE
1.00a - Blue Ball Enemies in Stage 1

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#47]
When bombing (with RencronA, at the very least), as of cad7f6881fd7c60bd0d370d7da420f75b4d9378d, the blue ball enemies go back to the top of the screen instead of continuing in their normal movement pattern. Is this intentional, and regardless of whether or not it is, is there a purpose or is this a bug?

**Comment by bluebear94** [comment]
Yes, RencronA's bomb is supposed to blow enemies upwards.
