### ISSUE TITLE
0.045tr - RygenA unfocused shot type obscures other objects on-screen

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#5]
Currently, RygenA's unfocused shot type, despite being rendered below bullets and most graphics, obscures other objects on screen.

Suggestion: In the player shot sheet, decrease alpha to around 150 and set the blend type to ADD_ARGB

Example:

```
ShotData{
    id = 1
    rect = (0,0,24,64)
    render = ADD_ARGB
    alpha=160
    collision = 8
}
```

**Comment by bluebear94** [comment]
Fixed in 84b84eeeec15d736297956d4b1b6033a1d672312.
