### ISSUE TITLE
1.00a - Stage 4 Boss's Opening Nonspell force-walls player

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#57]
The lasers in the Stage 4 Boss's opening non spell oftentimes forcefully wall the player and sandwich them between two lasers. To address them, sync the lasers to never collapse onto the player and/or provide breaks in the stream of homing bullets.

**Comment by Sparen** [comment]
Note: The second non spell is 1000x easier. Is this intentional?

**Comment by bluebear94** [comment]
It all depends on being on the right side of the laser.
