### ISSUE TITLE
1.00a - Stage 4 Boss Get Down spell is completely ridiculous

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#58]
It shouldn't even be there.

There are so many things wrong from this spell, from the multilingual text bubbles covering the spell name to the walls of impossible bullets, no hint of how to get by, etc.

Remove the spell or make it clear how to do it. This spell pisses me off with how unfair it is.

**Comment by bluebear94** [comment]
Fixed as of e33c372bc7f6b454a373a437c9024f7d8c0908b0 - the old spell is now limited to the Overdrive (which is meant to be ridiculously difficult anyway)
