### ISSUE TITLE
1.00a - Pausing during name input

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#59]
It is possible to have the pause menu open while inputting your name into the high score, as of cad7f6881fd7c60bd0d370d7da420f75b4d9378d.

![screen shot 2015-06-20 at 4 14 20 pm](https://cloud.githubusercontent.com/assets/5430590/8269074/715c688c-1767-11e5-9fd6-054e0b8f0466.png)

Is this intentional?

This screenshot was made by pausing the moment of death.

**Comment by bluebear94** [comment]
No.

**Comment by Sparen** [comment]
#60 
Referencing because this was probably how I got the manual to appear strangely, now that I think about it.
