### ISSUE TITLE
0.045tr - HiScore does not record when refusing to continue, then selecting retry script (main game)

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#6]
When you refuse to continue and then retry script, the high score of the previous run is not rendered on screen. This could be due to the score not saving upon refusal to continue, or due to some other issue.

**Comment by bluebear94** [comment]
Hmm, I tried it with RencronB Intense, got 972 billion before running out of lives on Stage 5, didn't continue, picked Retry Script, and the HiScore shown was 972 billion.

Player/Difficulty/Stage?

**Comment by Sparen** [comment]
Stage 1, I think. I don't remember which player. Probably Easy or Normal Mode

**Comment by bluebear94** [comment]
Are you sure you weren't number 2 on the scoreboard?

**Comment by Sparen** [comment]
???
I'm referring firstly to the Hi Score displayed on the STG_Frame, and I've git reset --hard every time you've sent out new updates, so... I doubt it.

**Comment by bluebear94** [comment]
I know which display you're mentioning. If you're number 2 on the scoreboard, then the number 1 score will stay on the STG_Frame.

Can you reproduce it on other difficulties?

**Comment by bluebear94** [comment]
This seems to happen only when there is no high score registered either before or after the play. The high score boards assume that the default number 1 position is 2^32 points, while the high score on the STG frame assumes that it is 0.
