### ISSUE TITLE
1.00a - Manual Contents incorrectly placed/not even on-screen

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#60]
As of cad7f6881fd7c60bd0d370d7da420f75b4d9378d, the manual text and other components are misplaced/are not even on the screen. 

To rectify, I suggest changing the render priority. If between 0.2 and 0.8, change to 0.9. Else, move within the 0.2 to 0.8 limits.

Manual was accessed from the End Scene.

**Comment by bluebear94** [comment]
You shouldn't even be able to access the manual from the end scene, only the pause scene, and accessing in the pause scene results in properly placed text.

**Comment by Sparen** [comment]
I don't even know what I did anymore
