### ISSUE TITLE
1.00a - Unable to Practice stages already seen in-game

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#62]
As of cad7f6881fd7c60bd0d370d7da420f75b4d9378d, as well as Bug #45, it is not possible to utilize practice mode for any stage other than stage 1.

**Comment by bluebear94** [comment]
You have to finish the stages in order to practice them.

**Comment by Sparen** [comment]
I finished the stages. They did not appear.

**Comment by bluebear94** [comment]
Are you trying to access them on the same difficulty as the one you played?

**Comment by Sparen** [comment]
Yes. With the same player.

**Comment by bluebear94** [comment]
Which player?

**Comment by Sparen** [comment]
I believe it was RencronA? I think? I always play as RencronA

**Comment by bluebear94** [comment]
Hmm, it seems that I can reproduce this bug.

**Comment by bluebear94** [comment]
I accidentally reversed the parameters to `selectStage` calls (lns 350 - 392), so the difficulty and character IDs were switched around.
