### ISSUE TITLE
1.00a - Hitting X on main menu should instantly move to 'Quit'

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#65]
Feature Request: Hit X on main menu to automatically move to 'Quit' option

**Comment by bluebear94** [comment]
I'm sorry, but there's no known way to implement this without doing so when hitting X to the main menu.

**Comment by Sparen** [comment]
I fixed it myself in 5eb88e0ee79ea11b5ee1444c0962940dfd70bee0

**Comment by bluebear94** [comment]
Sure, thanks!

**Comment by bluebear94** [comment]
Silly, that's what I tried! That just makes you select the "Quit" option whenever you press X to go back to the main menu.
