### ISSUE TITLE
1.00b - Stage 4 last? spell gimmick completely indecipherable

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#66]
So in 1.00b (as of 20c397b6208cdab24082a8785e73d716ca5213b3), there is a brand new last spell, making two survival cards in a row. Except this one has a gimmick that is not clear at all. There is a stream of bullets as well as what seems to be a net of lasers, and then bullets fire with gaps in them, depending on some color. But what color? When the ring is black, it shot orange or violet or something, and is there some kind of order?

Please spare players this pain, because nobody's going to make it past here.

**Comment by bluebear94** [comment]
You have to memorize each sequence of colors.
