### ISSUE TITLE
0.045tr - Player Invincibility Frames not known to player

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#7]
Currently upon death or bombing, there is no indication of whether or not the player is invincible, and it is not known to the player if the invincibility frames have been used up.

**Comment by bluebear94** [comment]
What would be the best (for lack of a better term) way to show the invincibility window?

**Comment by Sparen** [comment]
The standard is the have a magic circle whose radius is proportional to the number of remaining invincibility frames. Additionally, some people have the player graphic flash dark until the invincibility frames are over.
