### ISSUE TITLE
0.045tr - Vanar's graphic not centered within lifebar

### ISSUE THREAD

**Issue by Sparen** [bluebear94/cy05#9]
Vanar's graphic is not centered in the middle of her lifebar. This may be due to incorrect source/dest rect placement or due to the lifebar being placed incorrectly, although I believe it to be the former (I have not looked at the code)

**Comment by bluebear94** [comment]
Affects all bosses after Stage 1, excluding Vija.

Mernen's sprite was 96 pixels tall, but all others were 64.

**Comment by bluebear94** [comment]
Also, the third stage boss is technically called 32cf Vanar (Vanar #13007). Vanar is the name of the castle.

**Comment by Sparen** [comment]
Reopening due to presence of bug in cad7f6881fd7c60bd0d370d7da420f75b4d9378d

**Comment by bluebear94** [comment]
With which bosses does this bug still occur?
